version: "3"

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'

  backend:
    build:
      context: ./demain-brain/
      dockerfile: ./Dockerfile.development
    volumes:
      - ./demain-brain:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5000:5000'
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./demain-ideas-web/
      dockerfile: ./Dockerfile.development
    volumes:
      - ./demain-ideas-web:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend