version: "2"

services:  
  backend:
    build: ./backend/
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5000:5000'

  frontend:
    build: ./frontend/
    volumes: 
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports: 
      - '3000:3000'
    depends_on: 
      - backend